import { describe, it, expect } from "vitest";
import { diagnoseExtensions } from "../src/extensions/diagnose";
import { registryFake, targetEnvFake } from "./extensions-fixtures";
import { computeChecksum } from "../src/extensions/anchor";
import { insertAnchor } from "../src/extensions/anchor";

describe("AC-133 — doctor detects divergence without changing anything", () => {
  // SPECSFY: US-081 FR-083 FR-085 NFR-080 NFR-082 AC-133
  it("an artifact edited outside the CLI is named as divergent, with no write", () => {
    const originalContent = "# content generated by the CLI";
    const anchored = insertAnchor("", "extension", "my-extension", originalContent);
    const targetEnv = targetEnvFake({
      ".common-rules/extensions/my-hook.md": anchored.replace(originalContent, "# SOMEONE EDITED THIS BY HAND"),
    });
    const registry = registryFake([
      {
        category: "extension",
        name: "my-extension",
        target: "my-hook",
        content: originalContent,
        checksum: computeChecksum(originalContent),
        createdAt: "2026-09-02T00:00:00.000Z",
      },
    ]);

    const before = { ...targetEnv.files() };
    const divergent = diagnoseExtensions(registry, targetEnv, []);

    expect(divergent).toHaveLength(1);
    expect(divergent[0].name).toBe("my-extension");
    expect(divergent[0].reason).toBe("checksum-mismatch");
    expect(targetEnv.files()).toEqual(before);
  });
});
