"""Native editor hooks, generated from one definition.

A rule asks the agent to behave a certain way. A hook makes the editor enforce
it. That difference is the whole point of this module: guidance can be skipped,
skimmed or reasoned around, and a hook fires whether or not the agent
cooperates.

Every supported editor implements hooks, and all three disagree — on where the
config lives, on what the events are called, on how the config is nested, and on
what a handler must print to allow or deny. So a hook here is written once
against a canonical vocabulary, and this module translates it.

Translation happens at generation time, not at run time. Each editor gets a
self-contained script with the same logic body embedded in a wrapper that
already knows that editor's output format. There is no adapter chain, no
intermediate protocol, and no dependency beyond POSIX ``sh`` — a hook that
crashes because ``jq`` is missing is a hook that silently stops protecting
anything.

## Authoring contract

A hook's ``sh`` block is a fragment, not a whole script. It runs with:

* ``HOOK_INPUT``   — the raw event JSON the editor supplied on stdin
* ``HOOK_COMMAND`` — the shell command in question, extracted from that JSON
* ``HOOK_FILE``    — the file an edit touched, for events that concern one
* ``HOOK_EVENT``   — the canonical event name
* ``PROJECT_DIR``  — the project root

Prefer ``HOOK_COMMAND`` over matching ``HOOK_INPUT`` directly. The raw JSON also
contains prose — a commit message, a prompt — and matching against it fires on
text that merely mentions a command.

and it communicates by setting two variables:

* ``decision`` — ``allow`` (default), ``ask``, or ``deny``
* ``message``  — one line explaining a non-allow decision, or context to inject
"""

import json
import os
import re
import stat
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

MANAGED_MARKER = "common-rules:managed-hook"

CANONICAL_EVENTS = (
    "session-start",
    "before-prompt",
    "before-shell",
    "before-mcp",
    "after-file-edit",
    "stop",
)


@dataclass(frozen=True)
class EventMapping:
    """How one canonical event is expressed in one editor."""

    native: str
    #: Editor-side filter, where the editor needs one to narrow a broad event.
    matcher: Optional[str] = None


# Cursor: .cursor/hooks.json, schema version 1, camelCase events, each event
# holding a flat list of handlers.
CURSOR_EVENTS: dict[str, EventMapping] = {
    "session-start": EventMapping("sessionStart"),
    "before-prompt": EventMapping("beforeSubmitPrompt"),
    "before-shell": EventMapping("beforeShellExecution"),
    "before-mcp": EventMapping("beforeMCPExecution"),
    "after-file-edit": EventMapping("afterFileEdit"),
    "stop": EventMapping("stop"),
}

# Claude Code: .claude/settings.json, PascalCase events, handlers nested inside
# matcher groups. Shell and MCP calls are both PreToolUse, separated by matcher.
CLAUDE_EVENTS: dict[str, EventMapping] = {
    "session-start": EventMapping("SessionStart"),
    "before-prompt": EventMapping("UserPromptSubmit"),
    "before-shell": EventMapping("PreToolUse", matcher="Bash"),
    "before-mcp": EventMapping("PreToolUse", matcher="mcp__.*"),
    "after-file-edit": EventMapping("PostToolUse", matcher="Edit|Write"),
    "stop": EventMapping("Stop"),
}

# Antigravity: .agents/hooks.json, named hooks at the top level, and a smaller
# event set. `before-prompt` has no equivalent and is reported as unsupported
# rather than silently mapped onto something close.
ANTIGRAVITY_EVENTS: dict[str, EventMapping] = {
    "session-start": EventMapping("PreInvocation"),
    "before-shell": EventMapping("PreToolUse", matcher="run_command"),
    "before-mcp": EventMapping("PreToolUse", matcher="call_mcp_tool"),
    "after-file-edit": EventMapping("PostToolUse", matcher="edit_file"),
    "stop": EventMapping("Stop"),
}


# --------------------------------------------------------------- templates
#
# Each wrapper embeds the same logic body and differs only in what it prints.
# `deny` is expressed with exit code 2 where the editor supports it, which all
# three document as the blocking exit code.

_PREAMBLE = r"""#!/bin/sh
# {marker}
# Hook: {name}
# Event: {event} -> {native}
#
# {description}
#
# Generated by the common-rules MCP server. Edit the hook resource and re-run
# sync, not this file: regenerating overwrites it.

HOOK_INPUT=$(cat 2>/dev/null || printf '')
HOOK_EVENT='{event}'
PROJECT_DIR="${{CLAUDE_PROJECT_DIR:-$(pwd)}}"

# The shell command under consideration, pulled out of whatever JSON the editor
# sent. Every editor nests it differently but all of them spell the field
# "command", so one extraction covers all three. Matching the raw JSON instead
# would fire on text that merely mentions a command -- a commit message
# describing `rm -rf` -- and a guard that trips on ordinary work gets switched
# off, after which it guards nothing.
HOOK_COMMAND=$(printf '%s' "$HOOK_INPUT" | tr '\n' ' ' \
  | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\(\([^"\\]\|\\.\)*\)".*/\1/p')

# The file an edit touched, for events that concern one. Editors spell this
# "file_path" or "path"; both are tried.
HOOK_FILE=$(printf '%s' "$HOOK_INPUT" | tr '\n' ' ' \
  | sed -n 's/.*"\(file_path\|path\)"[[:space:]]*:[[:space:]]*"\(\([^"\\]\|\\.\)*\)".*/\2/p')

# The conversation transcript, for events that fire after the agent has said
# something. Without it a turn-end hook can only nag unconditionally, because
# it has no way to see whether what it is about to ask for was already done --
# which is how one shipped hook came to repeat itself eight turns running.
HOOK_TRANSCRIPT=$(printf '%s' "$HOOK_INPUT" | tr '\n' ' ' \
  | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\(\([^"\\]\|\\.\)*\)".*/\1/p')

# Set by the editor when a stop hook has already fired and continued the turn.
# A hook that ignores it can re-trigger itself indefinitely.
HOOK_STOP_ACTIVE=$(printf '%s' "$HOOK_INPUT" | tr '\n' ' ' \
  | sed -n 's/.*"stop_hook_active"[[:space:]]*:[[:space:]]*\(true\|false\).*/\1/p')

export HOOK_INPUT HOOK_EVENT PROJECT_DIR HOOK_COMMAND HOOK_FILE
export HOOK_TRANSCRIPT HOOK_STOP_ACTIVE

decision=allow
message=''

# ---- hook logic ----
{body}
# ---- end hook logic ----

# Strip characters that would break the JSON payload below. Messages are
# single-line by contract, so this loses nothing a hook needs to say.
message=$(printf '%s' "$message" | tr -d '"\\' | tr '\n' ' ')
"""

CURSOR_TEMPLATE = _PREAMBLE + r"""
case "$decision" in
  deny)
    printf '{{"permission":"deny","user_message":"%s","agent_message":"%s"}}\n' "$message" "$message"
    exit 0
    ;;
  ask)
    printf '{{"permission":"ask","user_message":"%s","agent_message":"%s"}}\n' "$message" "$message"
    exit 0
    ;;
  *)
    if [ -n "$message" ]; then
      printf '{{"permission":"allow","agent_message":"%s"}}\n' "$message"
    else
      printf '{{"permission":"allow"}}\n'
    fi
    exit 0
    ;;
esac
"""

CLAUDE_TEMPLATE = _PREAMBLE + r"""
case "$decision" in
  deny)
    printf '%s\n' "$message" >&2
    exit 2
    ;;
  ask)
    printf '{{"hookSpecificOutput":{{"hookEventName":"{claude_event}","permissionDecision":"ask","permissionDecisionReason":"%s"}}}}\n' "$message"
    exit 0
    ;;
  *)
    if [ -n "$message" ]; then
      printf '{{"hookSpecificOutput":{{"hookEventName":"{claude_event}","additionalContext":"%s"}}}}\n' "$message"
    fi
    exit 0
    ;;
esac
"""

ANTIGRAVITY_TEMPLATE = _PREAMBLE + r"""
case "$decision" in
  deny)
    printf '%s\n' "$message" >&2
    exit 2
    ;;
  ask)
    printf '%s\n' "$message" >&2
    exit 2
    ;;
  *)
    [ -n "$message" ] && printf '%s\n' "$message"
    exit 0
    ;;
esac
"""


@dataclass(frozen=True)
class IdeHookTarget:
    key: str
    label: str
    events: dict
    template: str
    config_path: str
    scripts_dir: str
    #: Claude writes hooks into a shared settings file; the others own theirs.
    shared_config: bool = False


HOOK_TARGETS: tuple[IdeHookTarget, ...] = (
    IdeHookTarget("cursor", "Cursor", CURSOR_EVENTS, CURSOR_TEMPLATE,
                  ".cursor/hooks.json", ".cursor/hooks"),
    IdeHookTarget("claude", "Claude Code", CLAUDE_EVENTS, CLAUDE_TEMPLATE,
                  ".claude/settings.json", ".claude/hooks", shared_config=True),
    IdeHookTarget("antigravity", "Antigravity", ANTIGRAVITY_EVENTS, ANTIGRAVITY_TEMPLATE,
                  ".agents/hooks.json", ".agents/hooks"),
)

TARGETS_BY_KEY = {target.key: target for target in HOOK_TARGETS}


class HookService:
    """Generates native hook configuration and scripts from hook resources."""

    def __init__(self, project_root: Optional[str] = None):
        self.project_root = Path(project_root) if project_root else Path(os.getcwd())

    def install(self, hooks: list[dict], ides: Optional[list[str]] = None) -> dict[str, Any]:
        """Writes hooks for each requested editor.

        ``hooks`` are parsed hook resources, each carrying its canonical event
        and a script body.
        """
        selected = [TARGETS_BY_KEY[k] for k in ides if k in TARGETS_BY_KEY] if ides else list(HOOK_TARGETS)

        result: dict[str, Any] = {"installed": [], "unsupported": [], "failed": []}

        for target in selected:
            supported = [h for h in hooks if h.get("event") in target.events]
            for hook in hooks:
                if hook.get("event") not in target.events:
                    result["unsupported"].append(
                        {
                            "ide": target.key,
                            "hook": hook.get("name"),
                            "event": hook.get("event"),
                            "reason": f"{target.label} has no equivalent of '{hook.get('event')}'",
                        }
                    )
            try:
                written = self._install_for(target, supported)
                result["installed"].append(written)
            except OSError as exc:
                result["failed"].append({"ide": target.key, "error": str(exc)})

        return result

    def _install_for(self, target: IdeHookTarget, hooks: list[dict]) -> dict[str, Any]:
        scripts_dir = self.project_root / target.scripts_dir
        scripts_dir.mkdir(parents=True, exist_ok=True)

        scripts = []
        for hook in hooks:
            mapping = target.events[hook["event"]]
            if hook.get("raw_command"):
                continue
            script = target.template.format(
                marker=MANAGED_MARKER,
                name=hook["name"],
                event=hook["event"],
                native=mapping.native,
                description=_one_line(hook.get("description", "")),
                body=hook["script"],
                claude_event=mapping.native,
            )
            path = scripts_dir / f"{hook['name']}.sh"
            path.write_text(script, encoding="utf-8")
            _make_executable(path)
            scripts.append(str(path.relative_to(self.project_root)))

        config_path = self.project_root / target.config_path
        config_path.parent.mkdir(parents=True, exist_ok=True)

        if target.key == "cursor":
            self._write_cursor(config_path, target, hooks)
        elif target.key == "claude":
            self._write_claude(config_path, target, hooks)
        else:
            self._write_antigravity(config_path, target, hooks)

        return {
            "ide": target.key,
            "config": target.config_path,
            "scripts": scripts,
            "hook_count": len(hooks),
        }

    # ------------------------------------------------------------- writers

    def _write_cursor(self, path: Path, target: IdeHookTarget, hooks: list[dict]) -> None:
        existing = _read_json(path) or {}
        events: dict[str, list] = {}

        # Preserve handlers this server did not generate.
        for event, handlers in (existing.get("hooks") or {}).items():
            kept = [h for h in handlers if not _is_managed_command(h.get("command"), target)]
            if kept:
                events[event] = kept

        for hook in hooks:
            mapping = target.events[hook["event"]]
            command = hook.get("raw_command")
            if command:
                command = command.replace("{ide}", target.key)
            else:
                command = f"{target.scripts_dir}/{hook['name']}.sh"
            handler: dict[str, Any] = {
                "command": command,
            }
            matcher = hook.get("matcher") or mapping.matcher
            if matcher:
                handler["matcher"] = matcher
            if hook.get("blocking"):
                handler["failClosed"] = True
            events.setdefault(mapping.native, []).append(handler)

        existing["version"] = 1
        existing["hooks"] = events
        _write_json(path, existing)

    def _write_claude(self, path: Path, target: IdeHookTarget, hooks: list[dict]) -> None:
        """Claude keeps hooks inside settings.json, which holds unrelated keys.

        Only the hooks this server generated are replaced; every other setting
        and every hand-written handler is left exactly as it was.
        """
        settings = _read_json(path) or {}
        events: dict[str, list] = {}

        for event, groups in (settings.get("hooks") or {}).items():
            kept_groups = []
            for group in groups:
                kept = [
                    h for h in group.get("hooks", [])
                    if not _is_managed_command(h.get("command"), target)
                ]
                if kept:
                    kept_groups.append({**group, "hooks": kept})
            if kept_groups:
                events[event] = kept_groups

        for hook in hooks:
            mapping = target.events[hook["event"]]
            command = hook.get("raw_command")
            if command:
                command = command.replace("{ide}", target.key)
            else:
                command = f"${{CLAUDE_PROJECT_DIR}}/{target.scripts_dir}/{hook['name']}.sh"
            handler = {
                "type": "command",
                "command": command,
            }
            matcher = hook.get("matcher") or mapping.matcher
            group = {"matcher": matcher or "*", "hooks": [handler]}
            events.setdefault(mapping.native, []).append(group)

        settings["hooks"] = events
        _write_json(path, settings)

    def _write_antigravity(self, path: Path, target: IdeHookTarget, hooks: list[dict]) -> None:
        """Antigravity names hooks at the top level, one key per hook."""
        existing = _read_json(path) or {}
        preserved = {
            name: spec
            for name, spec in existing.items()
            if not _antigravity_is_managed(spec, target)
        }

        for hook in hooks:
            mapping = target.events[hook["event"]]
            command = hook.get("raw_command")
            if command:
                command = command.replace("{ide}", target.key)
            else:
                command = f"./{target.scripts_dir}/{hook['name']}.sh"
            matcher = hook.get("matcher") or mapping.matcher
            preserved[hook["name"]] = {
                mapping.native: [
                    {
                        "matcher": matcher or ".*",
                        "hooks": [
                            {
                                "type": "command",
                                "command": command,
                            }
                        ],
                    }
                ]
            }

        _write_json(path, preserved)

    # ------------------------------------------------------------- removal

    def uninstall(self, ides: Optional[list[str]] = None) -> dict[str, Any]:
        """Removes generated hooks, leaving hand-written ones alone."""
        selected = [TARGETS_BY_KEY[k] for k in ides if k in TARGETS_BY_KEY] if ides else list(HOOK_TARGETS)
        removed = []
        for target in selected:
            config_path = self.project_root / target.config_path
            if config_path.exists():
                if target.key == "cursor":
                    self._write_cursor(config_path, target, [])
                elif target.key == "claude":
                    self._write_claude(config_path, target, [])
                else:
                    self._write_antigravity(config_path, target, [])
            scripts_dir = self.project_root / target.scripts_dir
            if scripts_dir.is_dir():
                for script in scripts_dir.glob("*.sh"):
                    if MANAGED_MARKER in script.read_text(encoding="utf-8", errors="replace"):
                        script.unlink()
                        removed.append(str(script.relative_to(self.project_root)))
                if not any(scripts_dir.iterdir()):
                    scripts_dir.rmdir()
        return {"removed": removed}


_MANAGED_COMMANDS = ("context-mode", "code-review-graph")


def _is_managed_command(command: Any, target: IdeHookTarget) -> bool:
    if not command:
        return False
    cmd = str(command)
    if target.scripts_dir in cmd:
        return True
    return any(tool in cmd for tool in _MANAGED_COMMANDS)


def _antigravity_is_managed(spec: Any, target: IdeHookTarget) -> bool:
    if not isinstance(spec, dict):
        return False
    spec_str = json.dumps(spec)
    if target.scripts_dir in spec_str:
        return True
    return any(tool in spec_str for tool in _MANAGED_COMMANDS)


def _one_line(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()


def _read_json(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def _write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _make_executable(path: Path) -> None:
    mode = os.stat(path).st_mode
    os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
