"""Export the resource catalogue into each editor's native format.

The server is one way to consume this kit. Sync is the other: it writes every
resource into the files the editor already reads, so the kit keeps working with
the MCP server switched off, uninstalled, or unavailable.

That matters for a reason beyond redundancy. Reaching resources through the
server costs a tool call and its response on every use. Reaching them natively
costs nothing at run time, because the editor loads them itself. Sync trades a
regeneration step for zero per-use overhead.

The export is fully mechanical — string transformation over parsed resources,
with no model involved — so running it is free.

## Mapping

Each editor supports a different set of concepts, so resources are mapped onto
the nearest native one rather than invented:

| Resource | Cursor | Claude Code | Antigravity |
|---|---|---|---|
| rule (Always) | `.cursor/rules/*.mdc` (alwaysApply) | `CLAUDE.md` block | `AGENTS.md` block |
| rule (other) | `.cursor/rules/*.mdc` | `.claude/skills/*/SKILL.md` | `.agents/skills/*/SKILL.md` |
| skill | `.cursor/skills/*/SKILL.md` | `.claude/skills/*/SKILL.md` | `.agents/skills/*/SKILL.md` |
| agent | `.cursor/agents/*.md` | `.claude/agents/*.md` | `.agents/skills/*/SKILL.md` |
| workflow, loop | skill | skill | skill |
| hook | `.cursor/hooks.json` | `.claude/settings.json` | `.agents/hooks.json` |

Workflows and loops become skills because no editor models them separately, and
a workflow is in practice an invocable procedure. Antigravity has no documented
subagent concept, so agents there become skills whose body states the persona.
"""

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from common_rules_server.service.hook_service import HookService
from common_rules_server.service.resource_service import ResourceService
from common_rules_server.util import managed_blocks
from common_rules_server.util.resource_parsing import COMMAND_TRIGGERS

GENERATED_HEADER = "<!-- generated by common-rules sync — edit the resource, not this file -->"
#: Distinct from the guidance block that setup writes into the same files.
BLOCK_NAME = "resources"
BLOCK_START = managed_blocks.start_marker(BLOCK_NAME)
BLOCK_END = managed_blocks.end_marker(BLOCK_NAME)

SKILL_KINDS = ("skill", "workflow", "loop")

#: Instructions that name a server tool stop working the moment the export is
#: read without the server running — the same class of dead end as naming a
#: template the export does not carry. Each entry says what to do instead.
TOOL_FALLBACKS: dict[str, str] = {
    "get_bdd_scenario": (
        "Read the feature file directly and work through it one scenario at a "
        "time, in order. Reading ahead defeats the point: a whole file gets "
        "skimmed and reported on in aggregate, where a single scenario has to "
        "be carried out. Each scenario needs the feature's `Background` to be "
        "executable, so keep that in view throughout."
    ),
    "get_context": (
        "The rules and skills beside this file are the catalogue, already "
        "resolved. Read them directly."
    ),
    "get_resource": (
        "The resource is a file beside this one. Open it."
    ),
    "create_resource": (
        "Write the file by hand into the project's resources directory, under a "
        "directory named for its kind, then re-run sync. Without the server "
        "nothing validates it, so check the frontmatter against a resource that "
        "already works."
    ),
    "setup_config": (
        "This needs the server. Configuration, hook installation and editor "
        "guidance are all written by it; there is no manual equivalent worth "
        "reproducing here."
    ),
}


@dataclass(frozen=True)
class SyncTarget:
    key: str
    label: str
    rules_dir: Optional[str]
    skills_dir: str
    agents_dir: Optional[str]
    #: Where Always-rules are concatenated when the editor has no rules folder.
    always_file: Optional[str]
    #: Whether the editor reads a `tools:` field in agent frontmatter and
    #: restricts the agent to what it names. Without it an exported agent
    #: inherits every tool, and a `constraints` line saying it must not edit
    #: files is prose the agent is asked to respect rather than a limit.
    tool_frontmatter: bool = False
    #: Whether the editor reads a `<chat-commands>` list out of its always-file
    #: and turns each entry into a typed slash command. Declared here rather
    #: than tested by key at the point of use, so adding a fourth editor is a
    #: row in this table instead of a condition buried in a writer.
    chat_commands: bool = False


SYNC_TARGETS: tuple[SyncTarget, ...] = (
    SyncTarget("cursor", "Cursor", ".cursor/rules", ".cursor/skills", ".cursor/agents", None),
    SyncTarget(
        "claude",
        "Claude Code",
        None,
        ".claude/skills",
        ".claude/agents",
        "CLAUDE.md",
        tool_frontmatter=True,
        chat_commands=True,
    ),
    SyncTarget("antigravity", "Antigravity", None, ".agents/skills", None, "AGENTS.md"),
)

TARGETS_BY_KEY = {target.key: target for target in SYNC_TARGETS}


class SyncService:
    def __init__(self, resources: ResourceService, project_root: Optional[str] = None):
        self.resources = resources
        self.project_root = Path(project_root) if project_root else Path(os.getcwd())

    def detect(self) -> list[SyncTarget]:
        """The editors this project shows evidence of using.

        Markers live in ``IdeService`` and are read from there rather than
        copied, so the two services cannot disagree about what counts as
        evidence that an editor is in use.
        """
        from common_rules_server.service.ide_service import IdeService

        detected = {t.key for t in IdeService(str(self.project_root)).detect()}
        return [target for target in SYNC_TARGETS if target.key in detected]

    def sync(self, ides: Optional[list[str]] = None, include_hooks: bool = True) -> dict[str, Any]:
        if ides:
            selected = [TARGETS_BY_KEY[k] for k in ides if k in TARGETS_BY_KEY]
            if not selected:
                return {
                    "synced": [],
                    "error": f"No known editor selected. Supported: {', '.join(TARGETS_BY_KEY)}.",
                }
        else:
            # Writing every layout because none was named leaves .cursor/ and
            # .agents/ in a project that only ever runs one editor — directories
            # the user did not ask for, will not read, and has to recognise as
            # ours before deleting. Configure what is in use; ask about the rest.
            selected = self.detect()
            if not selected:
                return {
                    "synced": [],
                    "detected": [],
                    "error": "No editor detected in this project.",
                    "hint": (
                        "Nothing was written. Name the editor explicitly — "
                        f"sync_to_ide(ides=[\"{next(iter(TARGETS_BY_KEY))}\"]) — "
                        f"choosing from: {', '.join(TARGETS_BY_KEY)}."
                    ),
                }

        catalogue = self.resources.load()
        records = sorted(
            catalogue["resources"].values(), key=lambda r: (r["kind"], r["name"])
        )
        hooks = [r for r in records if r["kind"] == "hook" and r.get("script")]

        result: dict[str, Any] = {"synced": [], "hooks": None, "total_resources": len(records)}

        for target in selected:
            result["synced"].append(self._sync_target(target, records))

        if include_hooks and hooks:
            result["hooks"] = HookService(str(self.project_root)).install(
                hooks, [t.key for t in selected]
            )

        result["note"] = (
            "Resources are now readable by the editor directly. Re-run sync after "
            "changing a resource; generated files are overwritten, so edit the "
            "resource rather than the output."
        )
        return result

    # ---------------------------------------------------------------- target

    def _sync_target(self, target: SyncTarget, records: list[dict]) -> dict[str, Any]:
        written: list[str] = []
        always_rules: list[dict] = []
        commands: list[dict] = []

        for record in records:
            kind = record["kind"]
            if kind == "hook":
                continue

            # Collected after the hook skip: a hook is fired by an event, never
            # typed, so it can never be a command.
            if _is_command(record):
                commands.append(record)

            if kind == "rule" and record.get("type") == "Always":
                always_rules.append(record)
                if target.rules_dir:
                    written.append(self._write_cursor_rule(target, record))
                continue

            if kind == "rule":
                if target.rules_dir:
                    written.append(self._write_cursor_rule(target, record))
                else:
                    written.append(self._write_skill(target, record))
                continue

            if kind == "agent" and target.agents_dir:
                written.append(self._write_agent(target, record))
                continue

            written.append(self._write_skill(target, record))

        if target.always_file and (always_rules or (target.chat_commands and commands)):
            written.append(self._write_always_file(target, always_rules, commands))

        return {
            "ide": target.key,
            "label": target.label,
            "files_written": len(written),
            "paths": written,
            "commands": [r["name"] for r in commands] if target.chat_commands else [],
        }

    # ---------------------------------------------------------------- writers

    def _write_cursor_rule(self, target: SyncTarget, record: dict) -> str:
        always = record.get("type") == "Always"
        front = [
            "---",
            f"description: {_one_line(record['description'])}",
            f"alwaysApply: {'true' if always else 'false'}",
            "---",
        ]
        content = "\n".join(front) + "\n\n" + GENERATED_HEADER + "\n\n" + self._body(record)
        return self._write(Path(target.rules_dir) / f"{record['name']}.mdc", content)

    def _write_skill(self, target: SyncTarget, record: dict) -> str:
        """Skills are a directory containing SKILL.md in all three editors."""
        front = [
            "---",
            f"name: {record['name']}",
            f"description: {_one_line(record['description'])}",
        ]
        # Claude lets a skill opt out of automatic invocation. Only a strictly
        # user-invoked skill wants that: `both` is listed as a command *and*
        # stays reachable from every can-invoke edge pointing at it.
        if target.chat_commands and record.get("trigger") == "user-invoked":
            front.append("disable-model-invocation: true")
        front.append("---")

        content = "\n".join(front) + "\n\n" + GENERATED_HEADER + "\n\n" + self._body(record)
        path = Path(target.skills_dir) / record["name"] / "SKILL.md"
        return self._write(path, content)

    def _write_agent(self, target: SyncTarget, record: dict) -> str:
        front = [
            "---",
            f"name: {record['name']}",
            f"description: {_one_line(record['description'])}",
        ]
        tools = record.get("tools")
        if isinstance(tools, list) and tools and target.tool_frontmatter:
            native = _native_tools(tools)
            if native:
                front.append(f"tools: {', '.join(native)}")
        front.append("---")

        body = [GENERATED_HEADER, ""]
        if record.get("persona"):
            body.append(_one_line(record["persona"]))
            body.append("")
        if record.get("constraints"):
            body.append("Constraints:")
            body.extend(f"- {c}" for c in record["constraints"])
            body.append("")
        body.append(self._body(record))

        content = "\n".join(front) + "\n\n" + "\n".join(body)
        return self._write(Path(target.agents_dir) / f"{record['name']}.md", content)

    def _write_always_file(
        self, target: SyncTarget, rules: list[dict], commands: list[dict]
    ) -> str:
        """Concatenates Always-rules into the file the editor reads every session.

        Only the managed block is replaced, so anything the user wrote in
        CLAUDE.md or AGENTS.md around it survives a re-sync.
        """
        sections = [
            "# Project orchestration",
            "",
            "Synced from the common-rules resource kit. Edit the resources and "
            "re-run sync; this block is regenerated.",
            "",
        ]
        for record in rules:
            sections.append(f"## {record['name']}")
            sections.append("")
            sections.append(self._body(record))
            sections.append("")

        if target.chat_commands and commands:
            sections.append(_render_commands(commands))
            sections.append("")

        path = self.project_root / target.always_file
        existing = path.read_text(encoding="utf-8") if path.exists() else ""

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            managed_blocks.merge(existing, "\n".join(sections), BLOCK_NAME),
            encoding="utf-8",
        )
        return target.always_file

    # ----------------------------------------------------------------- shared

    def _body(self, record: dict) -> str:
        """The instruction text, with the self-check appended.

        The self-check travels with the resource into every native format. It is
        the part most easily lost in translation and the part that makes the
        difference between a resource that was followed and one that was read.
        """
        parts = [record.get("body", "").strip()]

        if record.get("phases"):
            parts.append(_render_phases(record["phases"]))

        # The output template has to travel with the resource. Natively there is
        # no templates directory to fetch it from, so a synced skill that only
        # names its template leaves the agent with an instruction to produce a
        # shape it cannot see — and predictable output was the point.
        template = self.resources.read_template(
            (record.get("relationships") or {}).get("output")
        )
        if template:
            parts.append(
                "## Report format\n\n"
                "Produce the report in exactly this shape. Fill every slot; leave "
                "none of the `{{...}}` markers in the output.\n\n"
                "```markdown\n" + template.strip() + "\n```"
            )

        fallbacks = [
            (tool, guidance)
            for tool, guidance in TOOL_FALLBACKS.items()
            if tool in (record.get("body") or "")
        ]
        if fallbacks:
            lines = [
                "## Without the server",
                "",
                "This resource names tools the orchestration server provides. If it "
                "is not running, use these instead.",
                "",
            ]
            lines += [f"- **`{tool}`** — {guidance}" for tool, guidance in fallbacks]
            parts.append("\n".join(lines))

        if record.get("self_check"):
            parts.append(
                "## Self-check\n\n"
                "Before reporting this done, answer each of these honestly. If any "
                "answer is no, it is not done.\n\n"
                + "\n".join(f"- [ ] {q}" for q in record["self_check"])
            )

        return "\n\n".join(p for p in parts if p).strip() + "\n"

    def _write(self, relative: Path, content: str) -> str:
        path = self.project_root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return str(relative)

    # ------------------------------------------------------------------ clean

    def clean(self, ides: Optional[list[str]] = None) -> dict[str, Any]:
        """Removes generated files, identified by their generated header."""
        selected = (
            [TARGETS_BY_KEY[k] for k in ides if k in TARGETS_BY_KEY] if ides else list(SYNC_TARGETS)
        )
        removed = []
        for target in selected:
            for directory in (target.rules_dir, target.skills_dir, target.agents_dir):
                if not directory:
                    continue
                root = self.project_root / directory
                if not root.is_dir():
                    continue
                for path in sorted(root.rglob("*.md*")):
                    try:
                        if GENERATED_HEADER in path.read_text(encoding="utf-8", errors="replace"):
                            path.unlink()
                            removed.append(str(path.relative_to(self.project_root)))
                    except OSError:
                        continue
        HookService(str(self.project_root)).uninstall([t.key for t in selected])
        return {"removed": removed}


#: The kit names tools in its own lowercase vocabulary so a resource does not
#: have to know which editor will read it. An editor that restricts agents by
#: frontmatter needs its own names, and a value it does not recognise is
#: dropped rather than guessed at — a misspelt tool that silently widens an
#: agent's reach is worse than one that narrows it.
NATIVE_TOOL_NAMES: dict[str, str] = {
    "read": "Read",
    "write": "Write",
    "edit": "Edit",
    "grep": "Grep",
    "find": "Glob",
    "glob": "Glob",
    "execute": "Bash",
    "bash": "Bash",
    "git-diff": "Bash",
    "web-fetch": "WebFetch",
    "web-search": "WebSearch",
    "spawn-agent": "Agent",
}


def _native_tools(tools: list) -> list[str]:
    """Translates the kit's tool vocabulary into the editor's own names.

    Order is preserved and duplicates collapsed, because several kit names map
    onto one native tool (`execute` and `git-diff` are both `Bash`).

    Names with no mapping are dropped. Those are server-provided capabilities
    such as `code-review-graph`, which the editor does not gate on, and passing
    them through unchanged would produce a frontmatter value the editor rejects
    — taking the whole restriction with it.
    """
    native: list[str] = []
    for tool in tools:
        key = str(tool).strip().lower()
        mapped = NATIVE_TOOL_NAMES.get(key)
        if mapped is None and re.fullmatch(r"[A-Z][A-Za-z]+", str(tool)):
            mapped = str(tool)  # already an editor-native name
        if mapped and mapped not in native:
            native.append(mapped)
    return native


def _is_command(record: dict) -> bool:
    """Whether the user can type this resource's name as a command.

    Kind decides for three of them, because ``trigger`` alone under-reports.
    Workflows and loops carry no trigger — the field is only required of skills
    — yet a workflow is precisely a procedure a user starts by name. Agents
    carry none either, and an agent nobody can name is an agent that never runs:
    the editor knows it as a subagent type, but the user has no way to ask for
    one. Filtering on ``trigger`` alone silently drops all three groups.
    """
    if record["kind"] in ("workflow", "loop", "agent"):
        return True
    return record.get("trigger") in COMMAND_TRIGGERS


def _render_commands(commands: list[dict]) -> str:
    """The command list the editor reads out of its always-file.

    Ordering follows the catalogue's (kind, name) sort, so re-running sync over
    an unchanged kit produces a byte-identical block.

    Agents are marked, because typing one means something different from typing
    a skill: the skill runs here, the agent runs in its own context window as a
    subagent. Left unmarked they read as ordinary commands, and the delegation
    never happens.
    """
    agents = [r for r in commands if r["kind"] == "agent"]
    lines = [
        "## Custom Commands",
        "",
        "Type any of these directly. Each resolves to the resource of the same "
        "name beside this file. Entries marked `(subagent)` are spawned into "
        "their own context window rather than run in this one.",
        "",
        "<chat-commands>",
    ]
    for record in commands:
        mark = " (subagent)" if record["kind"] == "agent" else ""
        lines.append(f"- /{record['name']}{mark}: {_one_line(record['description'])}")
    lines.append("</chat-commands>")

    if agents:
        lines.extend(
            [
                "",
                "To delegate, spawn the agent by name — do not paste its "
                "instructions into this conversation. The separate context "
                "window is the point: it is what lets workers run in parallel "
                "without consuming the context you are working in.",
            ]
        )
    return "\n".join(lines)


def _render_phases(phases: list) -> str:
    lines = ["## Phases", "", "| Phase | Skills | Gate |", "|---|---|---|"]
    for phase in phases:
        if not isinstance(phase, dict):
            continue
        skills = ", ".join(phase.get("skills") or []) or "—"
        lines.append(f"| {phase.get('name', '')} | {skills} | {phase.get('gate', '—')} |")
    return "\n".join(lines)


def _one_line(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()
