name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: ''  # Definindo a variável globalmente no início do arquivo

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and Python 3.12
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
      - name: Update lockfile for test extras
        run: uv lock --extra test
      - name: Install dependencies and test extras
        run: uv sync --locked --extra test
      - name: Run tests with coverage and save output
        run: uv run pytest --cov=src/common_rules_server --cov-report=term-missing src/test/ | tee coverage.txt
      - name: Post coverage as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverage = fs.readFileSync('coverage.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Test Coverage Report\n\n\n\`\`\`\n${coverage}\n\`\`\``
            });
      - name: Debug PATH
        run: "echo \"PATH: $PATH\""
      - name: List .venv contents
        run: "ls -l .venv"
      - name: List .venv/bin contents
        run: "ls -l .venv/bin"
      - name: Check pytest executable
        run: "command -v pytest || true"

  build:
    runs-on: ubuntu-22.04
    outputs:
      api-version: ${{ steps.extract_version.outputs.VERSION }}
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from pyproject.toml
        id: extract_version
        run: |
          VERSION=$(grep -E '^version\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)"$' pyproject.toml | sed -E 's/^version\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+)"$/\1/')
          echo "Version extracted: $VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ vars.DOCKER_USERNAME && format('{0}/common-rules-server', vars.DOCKER_USERNAME) || 'common-rules-server' }}"
          echo "Debug: IMAGE_NAME = $IMAGE_NAME"
          TAG="${{ steps.extract_version.outputs.VERSION }}"
          docker build -t $IMAGE_NAME:$TAG .
          echo "Built Docker image: $IMAGE_NAME:$TAG"

      - name: Check if Docker Image Tag Exists
        id: check_tag_exists
        run: |
          IMAGE_NAME="${{ vars.DOCKER_USERNAME && format('{0}/common-rules-server', vars.DOCKER_USERNAME) || 'common-rules-server' }}"
          TAG="${{ steps.extract_version.outputs.VERSION }}"
          echo "Checking if Docker image tag $IMAGE_NAME:$TAG exists..."
          
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
            -u ${{ vars.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
            "https://hub.docker.com/v2/repositories/${{ vars.DOCKER_USERNAME && format('{0}/common-rules-server', vars.DOCKER_USERNAME) || 'common-rules-server' }}/tags/${{ steps.extract_version.outputs.VERSION }}/")
          
          if [ "$response" -eq 200 ]; then
            echo "Docker image tag $IMAGE_NAME:$TAG already exists. Skipping push."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Docker image tag $IMAGE_NAME:$TAG does not exist. Proceeding with push."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi          

      - name: Log in to Docker Hub
        if: env.TAG_EXISTS == 'false'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        if: env.TAG_EXISTS == 'false'
        run: |
          IMAGE_NAME="${{ vars.DOCKER_USERNAME && format('{0}/common-rules-server', vars.DOCKER_USERNAME) || 'common-rules-server' }}"
          echo "Debug: IMAGE_NAME in push_docker_image = $IMAGE_NAME"
          TAG="${{ steps.extract_version.outputs.VERSION }}"
          docker push $IMAGE_NAME:$TAG

  release:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:    
      - uses: actions/checkout@v4
       
      - name: Check if Tag Exists
        id: check_tag
        run: |
          echo "Checking if tag ${{ needs.build.outputs.api-version }} exists..."
          # Atualiza as tags no repositório
          git fetch --tags
          # Verifica se a tag já existe
          tag=$(git tag -l ${{ needs.build.outputs.api-version }})
          echo "tag: $tag"
          if [[ -n "$tag" ]]; then
            echo "Tag ${{ needs.build.outputs.api-version }} already exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag ${{ needs.build.outputs.api-version }} does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
      - name: Set Git User Identity
        run: |
          git config --global user.email "brunoxaviercalmon.br@gmail.com"
          git config --global user.name "${{ github.actor }}"

      - name: Create Tag
        if: env.TAG_EXISTS == 'false'
        run: |
          if [ "${{ env.TAG_EXISTS }}" = "false" ]; then
            echo "Creating and pushing tag: ${{ needs.build.outputs.api-version }}"
            git tag -a ${{ needs.build.outputs.api-version }} -m "Version ${{ needs.build.outputs.api-version }}"
            git push origin --force  ${{ needs.build.outputs.api-version }}
          else
            echo "Tag ${{ needs.build.outputs.api-version }} already exists, skipping tag creation."
          fi
